export enum SceneNames {
    MAIN = "main",
    NAME = "name",
    PHONE_NUMBER = "phoneNumber",
    REGISTER = "register",
    AGE = "age",
    LANGUAGE = "language",
    CHANNEL = "channel",
    COMMENT = "comment",
    VACANCY = "vacancy",
    SPECIALLY = "specially",
    REGION = "region",
    REGION2 = "region2",
    VACANCY_SEND = "vacancySend",
    REPLY = "reply",
    BACKEND = "backend",
    STATUS = "status",
    SALARY = "salary",
    CONTACT = "contact",
    VACANCY_PHONE = "vacancuPhone",
    VACANCY_TELEGRAM = "vacancyTelegram",
    FRONTEND = "frontend",
    SMM = "smm",
    MOBILE = 'mobile',
    DESIGN = "design",
    MANAGER = "manager",
    ADMINISTRATOR = "administrator",
    COPYWRITER = "copywriter",
    OFFICE_MANAGER = "officeManager",
    OPERATOR = "operator",
    ADMIN = "admin",
    MAIN_ADMIN = "mainAdmin",
    ADMIN_MESSAGE = "adminMessage",
    DIRECTION_TEXT = "directionText",
    SALARY_TEXT = "salaryText",


    ///////
    TECHNOLOGY = "technology",
    CONNECT = "connect",
    PLACE = "place",
    MIN_SUM = "minSum",
    MAX_SUM = "maxSum",
    PROFESSION = "profession",
    TIME_TO_CALL = "timeToCall",
    GOAL = "goal",
    SEND_TO_ADMIN = "sendToAdmin",
    REJECT_VACANSY = "rejectVacansy",
    CHOOSE_LANGUAGE = "chooseLanguage",
    CHOOSE_VACANSY = "chooseVacansy",
    PRICE = "price",
    DIRECTION = "direction",

    ////
    OFFICE_NAME = "officeName",
    MIN_PRICE = "minPrice",
    MAX_PRICE = "maxPrice",
    TECHNOLOGY_2 = "technology2",
    ADDRESS = "address",
    PLACE_2 = "plice2",
    RESPONSIBLE = "responsible",
    TIME_TO_CALL_2 = "timeToCall2",
    TIME_OF_WORK = "timeOfWork",
    CHANGE_LANGUAGE = "changeLanguage",
    DIRECTION_2 = "direction2",
    PRICE_2 = "price2",
    LINK = "link",
    ENTER_LINK = "enterLink",
    ADDITION_2 = "addition2",

    ///
    MY_VACANCY = "myVacancy",
    PRIVACY = "privacy"
}